### ISSUE TITLE
アカウント認証をバックエンドで実装

### ISSUE THREAD

**Issue by Mas423** [Mas423/book-management#17]
Auth0を使用せずバックエンドでアカウント認証ができるようにする。

**Comment by fooyama23** [comment]
https://zenn.dev/fooyama23/scraps/7ab765356e56d4

**Comment by fooyama23** [comment]
JWT認証について調べながら軽く実装。
https://zenn.dev/fooyama23/scraps/932a411d08ce53

**Comment by fooyama23** [comment]
`./`をモジュールの頭に付けると成功。
NG: `import passport from 'auth/security';`
OK: `import passport from './auth/security';`

tsconfig.jsonの`rootDir`、`baseUrl`の設定が関係しているか。
モジュールのパス: `src/auth/security.ts`
呼び出し元のパス: `src/app.ts`
- 失敗時
  - `rootDir`: `/`
    - srcのひとつ上
  - `baseUrl`: src`

**Comment by Mas423** [comment]
Postmanではバックエンドで認証ができることを確認済み。
次はフロントから呼べるようにする。
